#ifndef SYSCALLS_H
#define SYSCALLS_H

#include <unordered_map>
#include <string>
#include <vector>
#include <sys/syscall.h>

struct SyscallInfo {
    long number;
    std::vector<std::string> param_types;
};

const std::unordered_map<std::string, SyscallInfo> syscall_map = {
    {"read", {SYS_read, {"int", "void*", "size_t"}}},
    {"write", {SYS_write, {"int", "const void*", "size_t"}}},
    {"open", {SYS_open, {"const char*", "int", "mode_t"}}},
    {"close", {SYS_close, {"int"}}},
    {"stat", {SYS_stat, {"const char*", "struct stat*"}}},
    {"fstat", {SYS_fstat, {"int", "struct stat*"}}},
    {"lstat", {SYS_lstat, {"const char*", "struct stat*"}}},
    {"poll", {SYS_poll, {"struct pollfd*", "nfds_t", "int"}}},
    {"lseek", {SYS_lseek, {"int", "off_t", "int"}}},
    {"mmap", {SYS_mmap, {"void*", "size_t", "int", "int", "int", "off_t"}}},
    {"mprotect", {SYS_mprotect, {"void*", "size_t", "int"}}},
    {"munmap", {SYS_munmap, {"void*", "size_t"}}},
    {"brk", {SYS_brk, {"void*"}}},
    {"rt_sigaction", {SYS_rt_sigaction, {"int", "const struct sigaction*", "struct sigaction*", "size_t"}}},
    {"rt_sigprocmask", {SYS_rt_sigprocmask, {"int", "const sigset_t*", "sigset_t*", "size_t"}}},
    {"rt_sigreturn", {SYS_rt_sigreturn, {"unsigned long"}}},
    {"ioctl", {SYS_ioctl, {"int", "unsigned long", "..."}}},
    {"pread64", {SYS_pread64, {"int", "void*", "size_t", "off_t"}}},
    {"pwrite64", {SYS_pwrite64, {"int", "const void*", "size_t", "off_t"}}},
    {"readv", {SYS_readv, {"int", "const struct iovec*", "int"}}},
    {"writev", {SYS_writev, {"int", "const struct iovec*", "int"}}},
    {"access", {SYS_access, {"const char*", "int"}}},
    {"pipe", {SYS_pipe, {"int[2]"}}},
    {"select", {SYS_select, {"int", "fd_set*", "fd_set*", "fd_set*", "struct timeval*"}}},
    {"sched_yield", {SYS_sched_yield, {}}},
    {"mremap", {SYS_mremap, {"void*", "size_t", "size_t", "int", "void*"}}},
    {"msync", {SYS_msync, {"void*", "size_t", "int"}}},
    {"mincore", {SYS_mincore, {"void*", "size_t", "unsigned char*"}}},
    {"madvise", {SYS_madvise, {"void*", "size_t", "int"}}},
    {"shmget", {SYS_shmget, {"key_t", "size_t", "int"}}},
    {"shmat", {SYS_shmat, {"int", "const void*", "int"}}},
    {"shmctl", {SYS_shmctl, {"int", "int", "struct shmid_ds*"}}},
    {"dup", {SYS_dup, {"int"}}},
    {"dup2", {SYS_dup2, {"int", "int"}}},
    {"pause", {SYS_pause, {}}},
    {"nanosleep", {SYS_nanosleep, {"const struct timespec*", "struct timespec*"}}},
    {"getitimer", {SYS_getitimer, {"int", "struct itimerval*"}}},
    {"alarm", {SYS_alarm, {"unsigned int"}}},
    {"setitimer", {SYS_setitimer, {"int", "const struct itimerval*", "struct itimerval*"}}},
    {"getpid", {SYS_getpid, {}}},
    {"sendfile", {SYS_sendfile, {"int", "int", "off_t*", "size_t"}}},
    {"socket", {SYS_socket, {"int", "int", "int"}}},
    {"connect", {SYS_connect, {"int", "const struct sockaddr*", "socklen_t"}}},
    {"accept", {SYS_accept, {"int", "struct sockaddr*", "socklen_t*"}}},
    {"sendto", {SYS_sendto, {"int", "const void*", "size_t", "int", "const struct sockaddr*", "socklen_t"}}},
    {"recvfrom", {SYS_recvfrom, {"int", "void*", "size_t", "int", "struct sockaddr*", "socklen_t*"}}},
    {"sendmsg", {SYS_sendmsg, {"int", "const struct msghdr*", "int"}}},
    {"recvmsg", {SYS_recvmsg, {"int", "struct msghdr*", "int"}}},
    {"shutdown", {SYS_shutdown, {"int", "int"}}},
    {"bind", {SYS_bind, {"int", "const struct sockaddr*", "socklen_t"}}},
    {"listen", {SYS_listen, {"int", "int"}}},
    {"getsockname", {SYS_getsockname, {"int", "struct sockaddr*", "socklen_t*"}}},
    {"getpeername", {SYS_getpeername, {"int", "struct sockaddr*", "socklen_t*"}}},
    {"socketpair", {SYS_socketpair, {"int", "int", "int", "int[2]"}}},
    {"setsockopt", {SYS_setsockopt, {"int", "int", "int", "const void*", "socklen_t"}}},
    {"getsockopt", {SYS_getsockopt, {"int", "int", "int", "void*", "socklen_t*"}}},
    {"clone", {SYS_clone, {"int (*)(void*)", "void*", "int", "void*", "pid_t*", "void*", "pid_t*"}}},
    {"fork", {SYS_fork, {}}},
    {"vfork", {SYS_vfork, {}}},
    {"execve", {SYS_execve, {"const char*", "char *const[]", "char *const[]"}}},
    {"exit", {SYS_exit, {"int"}}},
    {"wait4", {SYS_wait4, {"pid_t", "int*", "int", "struct rusage*"}}},
    {"kill", {SYS_kill, {"pid_t", "int"}}},
    {"uname", {SYS_uname, {"struct utsname*"}}},
    {"semget", {SYS_semget, {"key_t", "int", "int"}}},
    {"semop", {SYS_semop, {"int", "struct sembuf*", "size_t"}}},
    {"semctl", {SYS_semctl, {"int", "int", "int", "..."}}},
    {"shmdt", {SYS_shmdt, {"const void*"}}},
    {"msgget", {SYS_msgget, {"key_t", "int"}}},
    {"msgsnd", {SYS_msgsnd, {"int", "const void*", "size_t", "int"}}},
    {"msgrcv", {SYS_msgrcv, {"int", "void*", "size_t", "long", "int"}}},
    {"msgctl", {SYS_msgctl, {"int", "int", "struct msqid_ds*"}}},
    {"fcntl", {SYS_fcntl, {"int", "int", "..."}}},
    {"flock", {SYS_flock, {"int", "int"}}},
    {"fsync", {SYS_fsync, {"int"}}},
    {"fdatasync", {SYS_fdatasync, {"int"}}},
    {"truncate", {SYS_truncate, {"const char*", "off_t"}}},
    {"ftruncate", {SYS_ftruncate, {"int", "off_t"}}},
    {"getdents", {SYS_getdents, {"unsigned int", "struct linux_dirent*", "unsigned int"}}},
    {"getcwd", {SYS_getcwd, {"char*", "size_t"}}},
    {"chdir", {SYS_chdir, {"const char*"}}},
    {"fchdir", {SYS_fchdir, {"int"}}},
    {"rename", {SYS_rename, {"const char*", "const char*"}}},
    {"mkdir", {SYS_mkdir, {"const char*", "mode_t"}}},
    {"rmdir", {SYS_rmdir, {"const char*"}}},
    {"creat", {SYS_creat, {"const char*", "mode_t"}}},
    {"link", {SYS_link, {"const char*", "const char*"}}},
    {"unlink", {SYS_unlink, {"const char*"}}},
    {"symlink", {SYS_symlink, {"const char*", "const char*"}}},
    {"readlink", {SYS_readlink, {"const char*", "char*", "size_t"}}},
    {"chmod", {SYS_chmod, {"const char*", "mode_t"}}},
    {"fchmod", {SYS_fchmod, {"int", "mode_t"}}},
    {"chown", {SYS_chown, {"const char*", "uid_t", "gid_t"}}},
    {"fchown", {SYS_fchown, {"int", "uid_t", "gid_t"}}},
    {"lchown", {SYS_lchown, {"const char*", "uid_t", "gid_t"}}},
    {"umask", {SYS_umask, {"mode_t"}}},
    {"gettimeofday", {SYS_gettimeofday, {"struct timeval*", "struct timezone*"}}},
    {"getrlimit", {SYS_getrlimit, {"int", "struct rlimit*"}}},
    {"getrusage", {SYS_getrusage, {"int", "struct rusage*"}}},
    {"sysinfo", {SYS_sysinfo, {"struct sysinfo*"}}},
    {"times", {SYS_times, {"struct tms*"}}},
    {"ptrace", {SYS_ptrace, {"enum __ptrace_request", "pid_t", "void*", "void*"}}},
    {"getuid", {SYS_getuid, {}}},
    {"syslog", {SYS_syslog, {"int", "const char*", "int"}}},
    {"getgid", {SYS_getgid, {}}},
    {"setuid", {SYS_setuid, {"uid_t"}}},
    {"setgid", {SYS_setgid, {"gid_t"}}},
    {"geteuid", {SYS_geteuid, {}}},
    {"getegid", {SYS_getegid, {}}},
    {"setpgid", {SYS_setpgid, {"pid_t", "pid_t"}}},
    {"getppid", {SYS_getppid, {}}},
    {"getpgrp", {SYS_getpgrp, {}}},
    {"setsid", {SYS_setsid, {}}},
    {"setreuid", {SYS_setreuid, {"uid_t", "uid_t"}}},
    {"setregid", {SYS_setregid, {"gid_t", "gid_t"}}},
    {"getgroups", {SYS_getgroups, {"int", "gid_t[]"}}},
    {"setgroups", {SYS_setgroups, {"size_t", "const gid_t*"}}},
    {"setresuid", {SYS_setresuid, {"uid_t", "uid_t", "uid_t"}}},
    {"getresuid", {SYS_getresuid, {"uid_t*", "uid_t*", "uid_t*"}}},
    {"setresgid", {SYS_setresgid, {"gid_t", "gid_t", "gid_t"}}},
    {"getresgid", {SYS_getresgid, {"gid_t*", "gid_t*", "gid_t*"}}},
    {"getpgid", {SYS_getpgid, {"pid_t"}}},
    {"setfsuid", {SYS_setfsuid, {"uid_t"}}},
    {"setfsgid", {SYS_setfsgid, {"gid_t"}}},
    {"getsid", {SYS_getsid, {"pid_t"}}},
    {"capget", {SYS_capget, {"cap_user_header_t", "cap_user_data_t"}}},
    {"capset", {SYS_capset, {"cap_user_header_t", "const cap_user_data_t"}}},
    {"rt_sigpending", {SYS_rt_sigpending, {"sigset_t*", "size_t"}}},
    {"rt_sigtimedwait", {SYS_rt_sigtimedwait, {"const sigset_t*", "siginfo_t*", "const struct timespec*", "size_t"}}},
    {"rt_sigqueueinfo", {SYS_rt_sigqueueinfo, {"pid_t", "int", "siginfo_t*"}}},
    {"rt_sigsuspend", {SYS_rt_sigsuspend, {"const sigset_t*", "size_t"}}},
    {"sigaltstack", {SYS_sigaltstack, {"const stack_t*", "stack_t*"}}},
    {"utime", {SYS_utime, {"const char*", "const struct utimbuf*"}}},
    {"mknod", {SYS_mknod, {"const char*", "mode_t", "dev_t"}}},
    {"uselib", {SYS_uselib, {"const char*"}}},
    {"personality", {SYS_personality, {"unsigned long"}}},
    {"ustat", {SYS_ustat, {"dev_t", "struct ustat*"}}},
    {"statfs", {SYS_statfs, {"const char*", "struct statfs*"}}},
    {"fstatfs", {SYS_fstatfs, {"int", "struct statfs*"}}},
    {"sysfs", {SYS_sysfs, {"int", "unsigned long", "unsigned long"}}},
    {"getpriority", {SYS_getpriority, {"int", "id_t"}}},
    {"setpriority", {SYS_setpriority, {"int", "id_t", "int"}}},
    {"sched_setparam", {SYS_sched_setparam, {"pid_t", "const struct sched_param*"}}},
    {"sched_getparam", {SYS_sched_getparam, {"pid_t", "struct sched_param*"}}},
    {"sched_setscheduler", {SYS_sched_setscheduler, {"pid_t", "int", "const struct sched_param*"}}},
    {"sched_getscheduler", {SYS_sched_getscheduler, {"pid_t"}}},
    {"sched_get_priority_max", {SYS_sched_get_priority_max, {"int"}}},
    {"sched_get_priority_min", {SYS_sched_get_priority_min, {"int"}}},
    {"sched_rr_get_interval", {SYS_sched_rr_get_interval, {"pid_t", "struct timespec*"}}},
    {"mlock", {SYS_mlock, {"const void*", "size_t"}}},
    {"munlock", {SYS_munlock, {"const void*", "size_t"}}},
    {"mlockall", {SYS_mlockall, {"int"}}},
    {"munlockall", {SYS_munlockall, {}}},
    {"vhangup", {SYS_vhangup, {}}},
    {"modify_ldt", {SYS_modify_ldt, {"int", "void*", "unsigned long"}}},
    {"pivot_root", {SYS_pivot_root, {"const char*", "const char*"}}},
    {"_sysctl", {SYS__sysctl, {"struct __sysctl_args*"}}},
    {"prctl", {SYS_prctl, {"int", "unsigned long", "unsigned long", "unsigned long", "unsigned long"}}},
    {"arch_prctl", {SYS_arch_prctl, {"int", "unsigned long"}}},
    {"adjtimex", {SYS_adjtimex, {"struct timex*"}}},
    {"setrlimit", {SYS_setrlimit, {"int", "const struct rlimit*"}}},
    {"chroot", {SYS_chroot, {"const char*"}}},
    {"sync", {SYS_sync, {}}},
    {"acct", {SYS_acct, {"const char*"}}},
    {"settimeofday", {SYS_settimeofday, {"const struct timeval*", "const struct timezone*"}}},
    {"mount", {SYS_mount, {"const char*", "const char*", "const char*", "unsigned long", "const void*"}}},
    {"umount2", {SYS_umount2, {"const char*", "int"}}},
    {"swapon", {SYS_swapon, {"const char*", "int"}}},
    {"swapoff", {SYS_swapoff, {"const char*"}}},
    {"reboot", {SYS_reboot, {"int", "int", "int", "void*"}}},
    {"sethostname", {SYS_sethostname, {"const char*", "size_t"}}},
    {"setdomainname", {SYS_setdomainname, {"const char*", "size_t"}}},
    {"iopl", {SYS_iopl, {"int"}}},
    {"ioperm", {SYS_ioperm, {"unsigned long", "unsigned long", "int"}}},
    {"create_module", {SYS_create_module, {"const char*", "size_t"}}},
    {"init_module", {SYS_init_module, {"void*", "unsigned long", "const char*"}}},
    {"delete_module", {SYS_delete_module, {"const char*", "int"}}},
    {"get_kernel_syms", {SYS_get_kernel_syms, {"struct kernel_sym*"}}},
    {"query_module", {SYS_query_module, {"const char*", "int", "void*", "size_t", "size_t*"}}},
    {"quotactl", {SYS_quotactl, {"int", "const char*", "int", "caddr_t"}}},
    {"nfsservctl", {SYS_nfsservctl, {"int", "struct nfsctl_arg*", "union nfsctl_res*"}}},
    {"getpmsg", {SYS_getpmsg, {"int", "struct strbuf*", "struct strbuf*", "int*", "int*"}}},
    {"putpmsg", {SYS_putpmsg, {"int", "const struct strbuf*", "const struct strbuf*", "int", "int"}}},
    {"afs_syscall", {SYS_afs_syscall, {"int", "int", "int", "int", "int", "int", "int"}}},
    {"tuxcall", {SYS_tuxcall, {"void*"}}},
    {"security", {SYS_security, {}}},
    {"gettid", {SYS_gettid, {}}},
    {"readahead", {SYS_readahead, {"int", "off64_t", "size_t"}}},
    {"setxattr", {SYS_setxattr, {"const char*", "const char*", "const void*", "size_t", "int"}}},
    {"lsetxattr", {SYS_lsetxattr, {"const char*", "const char*", "const void*", "size_t", "int"}}},
    {"fsetxattr", {SYS_fsetxattr, {"int", "const char*", "const void*", "size_t", "int"}}},
    {"getxattr", {SYS_getxattr, {"const char*", "const char*", "void*", "size_t"}}},
    {"lgetxattr", {SYS_lgetxattr, {"const char*", "const char*", "void*", "size_t"}}},
    {"fgetxattr", {SYS_fgetxattr, {"int", "const char*", "void*", "size_t"}}},
    {"listxattr", {SYS_listxattr, {"const char*", "char*", "size_t"}}},
    {"llistxattr", {SYS_llistxattr, {"const char*", "char*", "size_t"}}},
    {"flistxattr", {SYS_flistxattr, {"int", "char*", "size_t"}}},
    {"removexattr", {SYS_removexattr, {"const char*", "const char*"}}},
    {"lremovexattr", {SYS_lremovexattr, {"const char*", "const char*"}}},
    {"fremovexattr", {SYS_fremovexattr, {"int", "const char*"}}},
    {"tkill", {SYS_tkill, {"int", "int"}}},
    {"time", {SYS_time, {"time_t*"}}},
    {"futex", {SYS_futex, {"int*", "int", "int", "const struct timespec*", "int*", "int"}}},
    {"sched_setaffinity", {SYS_sched_setaffinity, {"pid_t", "size_t", "const cpu_set_t*"}}},
    {"sched_getaffinity", {SYS_sched_getaffinity, {"pid_t", "size_t", "cpu_set_t*"}}},
    {"set_thread_area", {SYS_set_thread_area, {"struct user_desc*"}}},
    {"io_setup", {SYS_io_setup, {"unsigned", "aio_context_t*"}}},
    {"io_destroy", {SYS_io_destroy, {"aio_context_t"}}},
    {"io_getevents", {SYS_io_getevents, {"aio_context_t", "long", "long", "struct io_event*", "struct timespec*"}}},
    {"io_submit", {SYS_io_submit, {"aio_context_t", "long", "struct iocb**"}}},
    {"io_cancel", {SYS_io_cancel, {"aio_context_t", "struct iocb*", "struct io_event*"}}},
    {"get_thread_area", {SYS_get_thread_area, {"struct user_desc*"}}},
    {"lookup_dcookie", {SYS_lookup_dcookie, {"u64", "char*", "size_t"}}},
    {"epoll_create", {SYS_epoll_create, {"int"}}},
    {"epoll_ctl_old", {SYS_epoll_ctl_old, {"int", "int", "int", "struct epoll_event*"}}},
    {"epoll_wait_old", {SYS_epoll_wait_old, {"int", "struct epoll_event*", "int", "int"}}},
    {"remap_file_pages", {SYS_remap_file_pages, {"void*", "size_t", "int", "ssize_t", "int"}}},
    {"getdents64", {SYS_getdents64, {"unsigned int", "struct linux_dirent64*", "unsigned int"}}},
    {"set_tid_address", {SYS_set_tid_address, {"int*"}}},
    {"restart_syscall", {SYS_restart_syscall, {}}},
    {"semtimedop", {SYS_semtimedop, {"int", "struct sembuf*", "size_t", "const struct timespec*"}}},
    {"fadvise64", {SYS_fadvise64, {"int", "off_t", "off_t", "int"}}},
    {"timer_create", {SYS_timer_create, {"clockid_t", "struct sigevent*", "timer_t*"}}},
    {"timer_settime", {SYS_timer_settime, {"timer_t", "int", "const struct itimerspec*", "struct itimerspec*"}}},
    {"timer_gettime", {SYS_timer_gettime, {"timer_t", "struct itimerspec*"}}},
    {"timer_getoverrun", {SYS_timer_getoverrun, {"timer_t"}}},
    {"timer_delete", {SYS_timer_delete, {"timer_t"}}},
    {"clock_settime", {SYS_clock_settime, {"clockid_t", "const struct timespec*"}}},
    {"clock_gettime", {SYS_clock_gettime, {"clockid_t", "struct timespec*"}}},
    {"clock_getres", {SYS_clock_getres, {"clockid_t", "struct timespec*"}}},
    {"clock_nanosleep", {SYS_clock_nanosleep, {"clockid_t", "int", "const struct timespec*", "struct timespec*"}}},
    {"exit_group", {SYS_exit_group, {"int"}}},
    {"epoll_wait", {SYS_epoll_wait, {"int", "struct epoll_event*", "int", "int"}}},
    {"epoll_ctl", {SYS_epoll_ctl, {"int", "int", "int", "struct epoll_event*"}}},
    {"tgkill", {SYS_tgkill, {"int", "int", "int"}}},
    {"utimes", {SYS_utimes, {"const char*", "const struct timeval[2]"}}},
    {"vserver", {SYS_vserver, {"void"}}},
    {"mbind", {SYS_mbind, {"void*", "unsigned long", "int", "const unsigned long*", "unsigned long", "unsigned"}}},
    {"set_mempolicy", {SYS_set_mempolicy, {"int", "const unsigned long*", "unsigned long"}}},
    {"get_mempolicy", {SYS_get_mempolicy, {"int*", "unsigned long*", "unsigned long", "void*", "unsigned long"}}},
    {"mq_open", {SYS_mq_open, {"const char*", "int", "mode_t", "struct mq_attr*"}}},
    {"mq_unlink", {SYS_mq_unlink, {"const char*"}}},
    {"mq_timedsend", {SYS_mq_timedsend, {"mqd_t", "const char*", "size_t", "unsigned", "const struct timespec*"}}},
    {"mq_timedreceive", {SYS_mq_timedreceive, {"mqd_t", "char*", "size_t", "unsigned*", "const struct timespec*"}}},
    {"mq_notify", {SYS_mq_notify, {"mqd_t", "const struct sigevent*"}}},
    {"mq_getsetattr", {SYS_mq_getsetattr, {"mqd_t", "const struct mq_attr*", "struct mq_attr*"}}},
    {"kexec_load", {SYS_kexec_load, {"unsigned long", "unsigned long", "struct kexec_segment*", "unsigned long"}}},
    {"waitid", {SYS_waitid, {"idtype_t", "id_t", "siginfo_t*", "int"}}},
    {"add_key", {SYS_add_key, {"const char*", "const char*", "const void*", "size_t", "key_serial_t"}}},
    {"request_key", {SYS_request_key, {"const char*", "const char*", "const char*", "key_serial_t"}}},
    {"keyctl", {SYS_keyctl, {"int", "..."}}},
    {"ioprio_set", {SYS_ioprio_set, {"int", "int", "int"}}},
    {"ioprio_get", {SYS_ioprio_get, {"int", "int"}}},
    {"inotify_init", {SYS_inotify_init, {}}},
    {"inotify_add_watch", {SYS_inotify_add_watch, {"int", "const char*", "uint32_t"}}},
    {"inotify_rm_watch", {SYS_inotify_rm_watch, {"int", "int"}}},
    {"migrate_pages", {SYS_migrate_pages, {"int", "unsigned long", "const unsigned long*", "const unsigned long*"}}},
    {"openat", {SYS_openat, {"int", "const char*", "int", "mode_t"}}},
    {"mkdirat", {SYS_mkdirat, {"int", "const char*", "mode_t"}}},
    {"mknodat", {SYS_mknodat, {"int", "const char*", "mode_t", "dev_t"}}},
    {"fchownat", {SYS_fchownat, {"int", "const char*", "uid_t", "gid_t", "int"}}},
    {"futimesat", {SYS_futimesat, {"int", "const char*", "const struct timeval[2]"}}},
    {"newfstatat", {SYS_newfstatat, {"int", "const char*", "struct stat*", "int"}}},
    {"unlinkat", {SYS_unlinkat, {"int", "const char*", "int"}}},
    {"renameat", {SYS_renameat, {"int", "const char*", "int", "const char*"}}},
    {"linkat", {SYS_linkat, {"int", "const char*", "int", "const char*", "int"}}},
    {"symlinkat", {SYS_symlinkat, {"const char*", "int", "const char*"}}},
    {"readlinkat", {SYS_readlinkat, {"int", "const char*", "char*", "size_t"}}},
    {"fchmodat", {SYS_fchmodat, {"int", "const char*", "mode_t", "int"}}},
    {"faccessat", {SYS_faccessat, {"int", "const char*", "int", "int"}}},
    {"pselect6", {SYS_pselect6, {"int", "fd_set*", "fd_set*", "fd_set*", "const struct timespec*", "const sigset_t*"}}},
    {"ppoll", {SYS_ppoll, {"struct pollfd*", "nfds_t", "const struct timespec*", "const sigset_t*", "size_t"}}},
    {"unshare", {SYS_unshare, {"int"}}},
    {"set_robust_list", {SYS_set_robust_list, {"struct robust_list_head*", "size_t"}}},
    {"get_robust_list", {SYS_get_robust_list, {"int", "struct robust_list_head**", "size_t*"}}},
    {"splice", {SYS_splice, {"int", "loff_t*", "int", "loff_t*", "size_t", "unsigned int"}}},
    {"tee", {SYS_tee, {"int", "int", "size_t", "unsigned int"}}},
    {"sync_file_range", {SYS_sync_file_range, {"int", "off64_t", "off64_t", "unsigned int"}}},
    {"vmsplice", {SYS_vmsplice, {"int", "const struct iovec*", "unsigned long", "unsigned int"}}},
    {"move_pages", {SYS_move_pages, {"int", "unsigned long", "const void**", "const int*", "int*", "int"}}},
    {"utimensat", {SYS_utimensat, {"int", "const char*", "const struct timespec[2]", "int"}}},
    {"epoll_pwait", {SYS_epoll_pwait, {"int", "struct epoll_event*", "int", "int", "const sigset_t*", "size_t"}}},
    {"signalfd", {SYS_signalfd, {"int", "const sigset_t*", "size_t"}}},
    {"timerfd_create", {SYS_timerfd_create, {"int", "int"}}},
    {"eventfd", {SYS_eventfd, {"unsigned int", "int"}}},
    {"fallocate", {SYS_fallocate, {"int", "int", "off_t", "off_t"}}},
    {"timerfd_settime", {SYS_timerfd_settime, {"int", "int", "const struct itimerspec*", "struct itimerspec*"}}},
    {"timerfd_gettime", {SYS_timerfd_gettime, {"int", "struct itimerspec*"}}},
    {"accept4", {SYS_accept4, {"int", "struct sockaddr*", "socklen_t*", "int"}}},
    {"signalfd4", {SYS_signalfd4, {"int", "const sigset_t*", "size_t", "int"}}},
    {"eventfd2", {SYS_eventfd2, {"unsigned int", "int"}}},
    {"epoll_create1", {SYS_epoll_create1, {"int"}}},
    {"dup3", {SYS_dup3, {"int", "int", "int"}}},
    {"pipe2", {SYS_pipe2, {"int[2]", "int"}}},
    {"inotify_init1", {SYS_inotify_init1, {"int"}}},
    {"preadv", {SYS_preadv, {"int", "const struct iovec*", "int", "off_t"}}},
    {"pwritev", {SYS_pwritev, {"int", "const struct iovec*", "int", "off_t"}}},
    {"rt_tgsigqueueinfo", {SYS_rt_tgsigqueueinfo, {"pid_t", "pid_t", "int", "siginfo_t*"}}},
    {"perf_event_open", {SYS_perf_event_open, {"struct perf_event_attr*", "pid_t", "int", "int", "unsigned long"}}},
    {"recvmmsg", {SYS_recvmmsg, {"int", "struct mmsghdr*", "unsigned int", "unsigned int", "struct timespec*"}}},
    {"fanotify_init", {SYS_fanotify_init, {"unsigned int", "unsigned int"}}},
    {"fanotify_mark", {SYS_fanotify_mark, {"int", "unsigned int", "uint64_t", "int", "const char*"}}},
    {"prlimit64", {SYS_prlimit64, {"pid_t", "int", "const struct rlimit64*", "struct rlimit64*"}}},
    {"name_to_handle_at", {SYS_name_to_handle_at, {"int", "const char*", "struct file_handle*", "int*", "int"}}},
    {"open_by_handle_at", {SYS_open_by_handle_at, {"int", "const struct file_handle*", "int"}}},
    {"clock_adjtime", {SYS_clock_adjtime, {"clockid_t", "struct timex*"}}},
    {"syncfs", {SYS_syncfs, {"int"}}},
    {"sendmmsg", {SYS_sendmmsg, {"int", "struct mmsghdr*", "unsigned int", "unsigned int"}}},
    {"setns", {SYS_setns, {"int", "int"}}},
    {"getcpu", {SYS_getcpu, {"unsigned*", "unsigned*", "struct getcpu_cache*"}}},
    {"process_vm_readv", {SYS_process_vm_readv, {"pid_t", "const struct iovec*", "unsigned long", "const struct iovec*", "unsigned long", "unsigned long"}}},
    {"process_vm_writev", {SYS_process_vm_writev, {"pid_t", "const struct iovec*", "unsigned long", "const struct iovec*", "unsigned long", "unsigned long"}}},
    {"kcmp", {SYS_kcmp, {"pid_t", "pid_t", "int", "unsigned long", "unsigned long"}}},
    {"finit_module", {SYS_finit_module, {"int", "const char*", "int"}}},
    {"sched_setattr", {SYS_sched_setattr, {"pid_t", "struct sched_attr*", "unsigned int"}}},
    {"sched_getattr", {SYS_sched_getattr, {"pid_t", "struct sched_attr*", "unsigned int", "unsigned int"}}},
    {"renameat2", {SYS_renameat2, {"int", "const char*", "int", "const char*", "unsigned int"}}},
    {"seccomp", {SYS_seccomp, {"unsigned int", "unsigned int", "void*"}}},
    {"getrandom", {SYS_getrandom, {"void*", "size_t", "unsigned int"}}},
    {"memfd_create", {SYS_memfd_create, {"const char*", "unsigned int"}}},
    {"kexec_file_load", {SYS_kexec_file_load, {"int", "int", "unsigned long", "const char*", "unsigned long"}}},
    {"bpf", {SYS_bpf, {"int", "union bpf_attr*", "unsigned int"}}},
    {"execveat", {SYS_execveat, {"int", "const char*", "char *const[]", "char *const[]", "int"}}},
    {"userfaultfd", {SYS_userfaultfd, {"int"}}},
    {"membarrier", {SYS_membarrier, {"int", "int"}}},
    {"mlock2", {SYS_mlock2, {"const void*", "size_t", "int"}}},
    {"copy_file_range", {SYS_copy_file_range, {"int", "loff_t*", "int", "loff_t*", "size_t", "unsigned int"}}},
    {"preadv2", {SYS_preadv2, {"int", "const struct iovec*", "unsigned long", "off_t", "int"}}},
    {"pwritev2", {SYS_pwritev2, {"int", "const struct iovec*", "unsigned long", "off_t", "int"}}},
    {"pkey_mprotect", {SYS_pkey_mprotect, {"void*", "size_t", "int", "int"}}},
    {"pkey_alloc", {SYS_pkey_alloc, {"unsigned int", "unsigned int"}}},
    {"pkey_free", {SYS_pkey_free, {"int"}}},
    {"statx", {SYS_statx, {"int", "const char*", "int", "unsigned int", "struct statx*"}}},
    {"io_pgetevents", {SYS_io_pgetevents, {"aio_context_t", "long", "long", "struct io_event*", "struct timespec*", "const struct __aio_sigset*"}}},
    {"rseq", {SYS_rseq, {"struct rseq*", "uint32_t", "int", "uint32_t"}}},
    {"pidfd_send_signal", {SYS_pidfd_send_signal, {"int", "int", "siginfo_t*", "unsigned int"}}},
    {"io_uring_setup", {SYS_io_uring_setup, {"u32", "struct io_uring_params*"}}},
    {"io_uring_enter", {SYS_io_uring_enter, {"unsigned int", "u32", "u32", "u32", "sigset_t*", "size_t"}}},
    {"io_uring_register", {SYS_io_uring_register, {"unsigned int", "unsigned int", "void*", "unsigned int"}}},
    {"open_tree", {SYS_open_tree, {"int", "const char*", "unsigned int"}}},
    {"move_mount", {SYS_move_mount, {"int", "const char*", "int", "const char*", "unsigned int"}}},
    {"fsopen", {SYS_fsopen, {"const char*", "unsigned int"}}},
    {"fsconfig", {SYS_fsconfig, {"int", "unsigned int", "const char*", "const void*", "int"}}},
    {"fsmount", {SYS_fsmount, {"int", "unsigned int", "unsigned int"}}},
    {"fspick", {SYS_fspick, {"int", "const char*", "unsigned int"}}},
    {"pidfd_open", {SYS_pidfd_open, {"pid_t", "unsigned int"}}},
    {"clone3", {SYS_clone3, {"struct clone_args*", "size_t"}}},
    {"close_range", {SYS_close_range, {"unsigned int", "unsigned int", "unsigned int"}}},
    {"openat2", {SYS_openat2, {"int", "const char*", "struct open_how*", "size_t"}}},
    {"pidfd_getfd", {SYS_pidfd_getfd, {"int", "int", "unsigned int"}}},
    {"faccessat2", {SYS_faccessat2, {"int", "const char*", "int", "int"}}},
    {"process_madvise", {SYS_process_madvise, {"int", "const struct iovec*", "size_t", "int", "unsigned int"}}},
    {"epoll_pwait2", {SYS_epoll_pwait2, {"int", "struct epoll_event*", "int", "const struct timespec*", "const sigset_t*", "size_t"}}},
    {"mount_setattr", {SYS_mount_setattr, {"int", "const char*", "unsigned int", "struct mount_attr*", "size_t"}}},
    {"quotactl_fd", {SYS_quotactl_fd, {"unsigned int", "int", "unsigned int", "void*"}}},
    {"landlock_create_ruleset", {SYS_landlock_create_ruleset, {"const struct landlock_ruleset_attr*", "size_t", "uint32_t"}}},
    {"landlock_add_rule", {SYS_landlock_add_rule, {"int", "enum landlock_rule_type", "const void*", "uint32_t"}}},
    {"landlock_restrict_self", {SYS_landlock_restrict_self, {"int", "uint32_t"}}},
    {"memfd_secret", {SYS_memfd_secret, {"unsigned int"}}},
    {"process_mrelease", {SYS_process_mrelease, {"int", "unsigned int"}}},
    {"futex_waitv", {SYS_futex_waitv, {"struct futex_waitv*", "unsigned int", "unsigned int", "struct timespec*", "clockid_t"}}},
    {"set_mempolicy_home_node", {SYS_set_mempolicy_home_node, {"unsigned long", "unsigned long", "unsigned long", "unsigned long", "unsigned int"}}},
};

#endif // SYSCALLS_H